= Mobile Walkthrough

In this walkthrough, we will deploy some mobile services, and run an app that can talk to these services.

[type=walkthroughResource, serviceName=openshift]
.OpenShift Project
****
* link:{openshift-host}/console/project/{walkthrough-namespace}/overview[OpenShift Project, window="_blank"]
****


[type=walkthroughResource, serviceName=openshift]
.OpenShift Service Catalog
****
* link:{openshift-host}/console/project/{walkthrough-namespace}/catalog[OpenShift Service Catalog, window="_blank"]
****


[type=walkthroughResource]
.Mobile Developer Console
****
* link:{route-mdc-server-host}[Mobile Developer Console, window="_blank"]
****


[time=5]
== Explore the Mobile Developer Console

The Mobile Developer Console is where mobile developers can view avaiable mobile services, bind them to their mobile apps and get the configurations for the bound mobile services.

=== Steps

. Go to link:{route-mdc-server-host}[Mobile Developer Console, window="_blank"], and you can login with your OpenShift credential.
. There should be no apps initially. Click on the `Create Mobile App` button to create a new app. Let's call it `demo`.
. When the app is created, click on it and it will bring you to the configure page. On the left hand side, you will see the instructions to add the SDKs to your client app. On the right hand side you will see the content of the configuration file to add to a client app. There should be no services listed in the configuration file.
. Go to the `Mobile Services` tab, and you should see there are a few services listed in the `Unbound Services` section.
. Bind the `Mobile Metrics` and `Identity Management` services to the app by clicking on the "Bind To App" buttons. Use the default binding options, and once the bindings are completed, you will see them in the `Bound Services` section. 
. Now to back to the `Configuration` tab again, you will see the `mobile-services.json` file is updated with information about the bound services. If you expand the row for each service, you will see the links to each of the service. Feel free to click on the links and explore the dashboard for each of the service.

[time=5]
== Deploy a new sync backend server

As part of the mobile services product, we also provide a set of libaries that will allow developers to easily create mobile apps that can sync data to the their backend. The libaries are based on the popular Apollo GraphQL server, with the following additional functionalities:

. Offline Support
. Conflict Resolution
. Easy integration with other mobile services

Let's try it out.

=== Steps

. Go the link:{openshift-host}/console/project/{walkthrough-namespace}/catalog[Service Catalog, window="_blank"] page of the OpenShift project, and click on the `Mobile` tab and choose `Sync App`.
. Use the following configurations for the sync app, and leave the rest empty:
.. Sync Application Docker image: `docker.io/weilee/sync-server-example-app`
.. Sync Application health endpoint: `health`
.. Sync App Port: `4000`
.. Sync App GraphQL Endpoint: `graphql`
.. SQL Server Hostname: `postgresql`
.. SQL Server Port: `5432`
.. SQL Server Username: `postgres`
.. SQL Server Password: `postgres`
.. Database name: `postgres`
. Do not bind the service to any app yet. Complete the wizard and wait for the service to be deployed.
. Try out the link:{route-sync-app-host}/graphql[GraphQL playground, window="_blank"].
. Paste in the following query/mutation into the text edit:
+
----
query listTasks {
  allTasks {
    title,
    description,
    id
  }
}

mutation createTask {
  createTask(title: "complete the walkthrough", description: "complete the mobile walk through") {
    title,
    description,
    version,
    id
  }
}
----
+
and try execute them. Feel free to explore the schema and add more queries and mutations.
. Go to link:{route-mdc-server-host}[Mobile Developer Console, window="_blank"] again, create a new app called `todoapp`, and bind the app to the newly created sync server.

[time=10]
== Run the sync client app

=== Steps

1. Clone the sync client app locally.
2. Follow the instructions, copy the `mobile-services.json` file to the client app.
3. Start the app. Go to your browser and view the app. Try create a task.
4. Open the app again in a new incognito tab, and try create tasks in both tabs.

[time=10]
== Check the auditlogs and metrics

Check the Grafana graph and the audit logs for sync.

=== Steps


[time=10]
== Protect the sync app by Keycloak

The sync server app is not protected at the moment, let's bind it with Keycloak and protect the endpoints.

=== Steps

1. Go to the project on Openshift, find `Keycloak` in the "Provisioned Services" section, and create a new binding.
2. In the dialog, enter the name of the sync app as the client id, and choose "public" type. Create the binding.
3. Wait for it to be completed, then go to secrets view and find the newly created secret. Add the secret to the sync app, and mount it to a location. Note it will be mounted as a directory to the pod.
4. Update the "KEYCLOAK_CONFIG" environment variable of the sync server app to point it to the "config" file inside the mounted secret directory. Add the NODE_TLS_REJECT_UNAUTHORIZED=0 env var if self signed cert is used.
5. Try the client app again, you will get an error now because you are not logged in.
6. Check out <this branch> of the client app, build it and run it again. When you start it, you will need to login. To get it work, we need to configure keycloak first.
7. Go to keycloak admin, find the realm that is matching the openshift namespace, and the client is that created by the binding. In the settings tab, add a new valid redirect url. In the roles tab, and a new role. Create a new user, set a password, and assign a new role to the user.
8. Go back to the app and try login. New you should be able to creat tasks again.
